version: '3.9'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.32
    container_name: "bootcamp"
    volumes:
      - mysql-bootcamp:/var/lib/mysql
      - "./images/mysql/init:/docker-entrypoint-initdb.d"
      - "./images/mysql/configuration:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "pqwemlkc31fsw"
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - '3320'
volumes:
  mysql-bootcamp:
    driver: local